#!/usr/bin/env python3
"""Generate the data files the web app embeds.

    web/src/gazetteer.js   country and region boxes, from eqmon/regions.py
    web/src/landdata.js    world coastlines, zlib-compressed and base64'd

The gazetteer is generated rather than copied so the terminal app and the web
app can never disagree about what "japan" or "ring of fire" means.

Coastlines come from world-atlas ``land-110m`` (Natural Earth 1:110m land,
public domain). Pass a local copy with ``--topo`` or let this download it once:

    python3 tools/build_webdata.py
    python3 tools/build_webdata.py --topo path/to/land-110m.json
"""

import argparse
import base64
import json
import os
import sys
import urllib.request
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from eqmon import regions  # noqa: E402

TOPO_URL = "https://cdn.jsdelivr.net/npm/world-atlas@2/land-110m.json"
OUT = os.path.join(ROOT, "web", "src")


def write_gazetteer():
    boxes = {}
    for key, value in regions.BOXES.items():
        boxes[key] = [list(b) for b in value] if isinstance(value[0], tuple) \
            else list(value)
    payload = {"boxes": boxes, "aliases": regions.ALIASES,
               "display": regions.DISPLAY}
    text = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    path = os.path.join(OUT, "gazetteer.js")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("/* Generated by tools/build_webdata.py from eqmon/regions.py. "
                 "Do not edit. */\n")
        fh.write("var QB_DATA = %s;\n" % text)
        fh.write("if (typeof module === 'object' && module.exports) "
                 "module.exports = QB_DATA;\n")
    print("gazetteer.js  %d regions, %d aliases, %.1f kB"
          % (len(boxes), len(regions.ALIASES), os.path.getsize(path) / 1024.0))


def write_land(topo_path):
    if topo_path:
        raw = open(topo_path, "rb").read()
    else:
        print("downloading", TOPO_URL)
        raw = urllib.request.urlopen(TOPO_URL, timeout=60).read()
    topo = json.loads(raw)
    assert topo.get("type") == "Topology" and "land" in topo["objects"]
    minified = json.dumps(topo, separators=(",", ":")).encode("utf-8")
    blob = base64.b64encode(zlib.compress(minified, 9)).decode("ascii")
    path = os.path.join(OUT, "landdata.js")
    with open(path, "w") as fh:
        fh.write("/* Generated by tools/build_webdata.py. Natural Earth 1:110m "
                 "land (public domain),\n   via world-atlas, as zlib+base64 "
                 "TopoJSON. Do not edit. */\n")
        fh.write("var QB_LAND = (\n")
        for i in range(0, len(blob), 100):
            fh.write('  "%s"%s\n' % (blob[i:i + 100],
                                     " +" if i + 100 < len(blob) else ""))
        fh.write(");\n")
        fh.write("if (typeof module === 'object' && module.exports) "
                 "module.exports = QB_LAND;\n")
    print("landdata.js   %d B topojson -> %d B zlib -> %.1f kB base64"
          % (len(minified), len(zlib.compress(minified, 9)),
             os.path.getsize(path) / 1024.0))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawTextHelpFormatter)
    ap.add_argument("--topo", help="local land-110m.json (skips the download)")
    args = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    write_gazetteer()
    write_land(args.topo)


if __name__ == "__main__":
    main()
